# Generated by Django 4.2.4 on 2023-09-22 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_userprofile_default_doctor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='default_prescription',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=25, null=True),
        ),
    ]
