# Generated by Django 4.2.4 on 2023-09-22 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_userprofile_default_pharmacy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='default_pharmacy',
            field=models.CharField(blank=True, choices=[('Pharmacy', (('Beacons', 'Beacons Pharmacy'), ('Dowlais', 'Dowlais Pharmacy'), ('Georgetown', 'Georgetown Pharmacy'), ('Keir Hardie', 'Keir Hardie Pharmacy'), ('Lewis', 'Lewis Pharmacy')))], max_length=20, null=True),
        ),
    ]
