# Generated by Django 4.2.4 on 2023-09-05 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='pharmacy',
            field=models.CharField(choices=[('Beacons', 'Beacons'), ('Dowlais', 'Dowlais'), ('Georgetown', 'Georgetown'), ('Keir Hardie', 'Keir Hardie'), ('Lewis', 'Lewis')], default='Doctor care', max_length=50),
        ),
    ]
