# Generated by Django 4.2.4 on 2023-09-07 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_appointment_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='preference',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=50),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='pharmacy',
            field=models.CharField(choices=[('Beacons', 'Beacons'), ('Dowlais', 'Dowlais'), ('Georgetown', 'Georgetown'), ('Keir Hardie', 'Keir Hardie'), ('Lewis', 'Lewis')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.CharField(choices=[('3 PM', '3 PM'), ('3:30 PM', '3:30 PM'), ('4 PM', '4 PM'), ('4:30 PM', '4:30 PM'), ('5 PM', '5 PM'), ('5:30 PM', '5:30 PM'), ('6 PM', '6 PM')], default='9 AM', max_length=10),
        ),
    ]
